server:
  port: 8888

logging:
  file: userManager.log
    path: logs


spring:
  application:
    name: userManager
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course
    username: root
    password: admin


mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    -mapper/*